name: Update libphonenumber

on:
  schedule:
    - cron:  '0 0 * * 1'
  workflow_dispatch:

jobs:
  update:
    name: Update libphonenumber
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run update
